name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: go

    - name: Build
      run: go build -v ./...

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

    - name: Run migrations
      run: go run main.go -migrateOnly
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres?sslmode=disable

    - name: Test
      run: go test -v ./... -covermode=atomic -coverprofile=coverage.txt -coverpkg=./...
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres?sslmode=disable

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.txt
        verbose: true

